### ISSUE TITLE
LuaCacheProfile command errors if config is reloaded

### ISSUE THREAD

**Issue by akinsho** [lewis6991/impatient.nvim#16]
Hi,

When reloading my config file I've noticed that having
```lua
require('impatient').enable_profile()
```
in my `init.lua` causes an error if I reload this file because the `LuaCacheProfile` command is missing a bang allowing it be redefined.

```
Error executing lua .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:44: Vim(command):E174: Command already exists: add ! to replace it: LuaCacheProfile lua _G.__luacache.print_profile()
```

**Comment by lewis6991** [comment]
PR's welcome 😉

**Comment by akinsho** [comment]
Sorry was at work when I noticed this otherwise I would have just sent a PR instead, can't really do open source work on my work machine.

**Comment by akinsho** [comment]
Thanks 🚀
