### ISSUE TITLE
Use `$APPDIR` to cache appimage's `$VIMRUNTIME` files

### ISSUE THREAD

**Issue by chase** [lewis6991/impatient.nvim#18]
We could potentially check if a path is under `$APPDIR` (according to https://docs.appimage.org/packaging-guide/environment-variables.html#type-2-appimage-runtime) then on the next load, just replace any part of the path under `$APPDIR` to get positive path matches

**Comment by lewis6991** [comment]
Sounds like a good idea.

I currently don't have access to a machine that can run the app images (until atleast https://github.com/neovim/neovim/pull/15542 is done), so would need someone to implement this.
