### ISSUE TITLE
E5560: nvim_get_option must not be called in a lua loop callback

### ISSUE THREAD

**Issue by oblitum** [lewis6991/impatient.nvim#23]
I've hit this after the latest updates, while using nvim-dap (never happened before):

```text
Error executing luv callback:
.../site/pack/packer/start/impatient.nvim/lua/impatient.lua:138: E5560: nvim_get_option must not be called in a lua loop callback
```

nvim 0.5

**Comment by lewis6991** [comment]
Thanks. Just fixed this but note that `require` in a fast callback currently has a known [issue](https://github.com/neovim/neovim/issues/15147) in Neovim so nvim-dap should probably be fixed as well.

**Comment by oblitum** [comment]
Working fine now, thx.
