### ISSUE TITLE
Does impatient cache opt as well?

### ISSUE THREAD

**Issue by kkharji** [lewis6991/impatient.nvim#27]
Hey @lewis6991  thanks a lot for taking the time to put this together.

I wonder if opt lua files are cached as well, because I feel this might be the cause of impatient taking longer time to load. before it was like 3.1ms

```
impatient                                      │     mixed │   0.4379ms │   5.7322ms │   6.1700ms │
```

**Comment by lewis6991** [comment]
Yes, opt files are cached as well. Everything loaded with `require` gets cached.
