### ISSUE TITLE
attempt to perform arithmetic on field 'exec' (a nil value)

### ISSUE THREAD

**Issue by yujinyuz** [lewis6991/impatient.nvim#30]
When I use
```
require('impatient').enable_profile()
```

I get an error
```
packer.nvim: Error running config for nvim-lspconfig: ...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:148: attempt to perform arithmetic on field 'exec' (a nil value)
```

I don't have this proble with

```
require('impatient')
```

**Comment by lewis6991** [comment]
I don't get this error. You need to provide more details.

**Comment by megalithic** [comment]
Samesies; I'm getting this only for `enable_profile()`;

I'm very simply calling the following, from my init.lua at the root of my nvim:

```lua
local ok, impatient = pcall(require, "impatient")
if ok then
  impatient.enable_profile()
end
```

Same error as @yujinyuz

**Comment by yujinyuz** [comment]
I don't get the errors anymore but I get this message

```
impatient: [error] dependency config/lsp of workspace does not have profile results. Results will be inaccurate
impatient: [error] dependency packer_compiled of workspace does not have profile results. Results will be inaccurate
```

What should I do in order to resolve this?

This is what have

```
-- Load globals
require('globals')
-- Make `vim.keymap` available
require('utils._keymap_port')
-- Load global helpers
require('utils')
require('packer_compiled')
require('impatient').enable_profile()
-- Load options
require('options')
-- Load plugins last
require('plugins')
```

Is this right?

**Comment by lewis6991** [comment]
From the README:

> impatient needs to be setup before any other lua plugin is loaded so it is recommended you add the following near the start of your init.vim.

Yet in your config you are requiring several modules before impatient.

Move impatient to the top.

**Comment by yujinyuz** [comment]
@lewis6991 I tried moving `require('impatient').enable_profile()` to the top but still getting the same error

**Comment by lewis6991** [comment]
The error happens because there is a require happening before impatient is loaded.

**Comment by yujinyuz** [comment]
Can't seem to figure out why. I've already moved the `require('impatient').enable_profile()` to the top most of my init.lua but I'm still getting the same error.

I'll just remove the `.enable_profile()` for now and will try to investigate further

**Comment by lewis6991** [comment]
I did some more tweaks with https://github.com/lewis6991/impatient.nvim/commit/561b86e5602def047010d451c3e7977a65982788 and it will hopefully fix the issue you are seeing.
