### ISSUE TITLE
amazing!!! But is require('packer_compiled') neccessary? 

### ISSUE THREAD

**Issue by finviman** [lewis6991/impatient.nvim#31]
I have config like this
```lua
require('impatient')
-- require('packer_compiled')
  use {'lewis6991/impatient.nvim',config = {
    compile_path = '~/.config/nvim/lua/plugin/packer_compiled.lua'
  }
```
and the startup speed is nearly 2X faster than before.
but `require('packer_compiled')` report an error:

module 'packer_compiled' not found

so i comment it.

**Comment by bangedorrunt** [comment]
That `compile_path` is supposed to be setup by `packer`, not by `impatient`

**Comment by alexzanderr** [comment]
still doesnt work with this config
```lua
	use 'lewis6991/impatient.nvim'
	config = {
		-- Move to lua dir so impatient.nvim can cache it
		compile_path = vim.fn.stdpath('config')..'/lua/packer_compiled.lua'
	}

**Comment by alexzanderr** [comment]
but its weird, without this require packer compiled, the plugins works and the startuptime is insanely fast

**Comment by lewis6991** [comment]
Did you make sure to delete the old `packer_compiled.lua`? And did you also run `:PackerCompile` with the new config?

**Comment by lewis6991** [comment]
Also note that the `packer_compile.lua` trick isn't necessary, it just allows that specific module to be cached.

**Comment by finviman** [comment]
> That `compile_path` is supposed to be setup by `packer`, not by `impatient`

Yes, I was wrong
