### ISSUE TITLE
attempt to call field 'encode' (a nil value)

### ISSUE THREAD

**Issue by quantum-booty** [lewis6991/impatient.nvim#38]
Nvim version: NVIM v0.6.0-dev+525-ge921e98ce

```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:243: attempt to call field 'encode' (a nil value)
```

minimal config:
```
require('packer').startup({function()
    use 'wbthomason/packer.nvim'
    use 'lewis6991/impatient.nvim'
end,
    config = {
        compile_path = vim.fn.stdpath('config')..'/lua/packer_compiled.lua',
    }
})

require('impatient')
require('packer_compiled')
```

**Comment by ofseed** [comment]
I happened to have the same problem just now...

**Comment by zeitchef** [comment]
Me too...

**Comment by ihasdapie** [comment]
I think it has to do with this commit since changing it back to `.pack` and `.unpack` worked for me.
https://github.com/lewis6991/impatient.nvim/commit/04320ed513643d7d869775f40529e41a7683648f

 Updating `mpack` via luarocks to `1.09` does not fix the issue either and I'm on the latest neovim 0.6 nightly.

Not quite sure at what version of `mpack` the (decode/encode)/(unpack/pack) renaming happened but it doesn't seem to be bundled with neovim at the moment.

**Comment by ihasdapie** [comment]
Actually, it looks like https://github.com/neovim/neovim/pull/16175 was merged just 5 hours ago so maybe this will be fixed for `nightly` users by neovim's next CI run? Otherwise it would probably be good at have a little guard against people running older version of neovim.

**Comment by ofseed** [comment]
> Actually, it looks like [neovim/neovim#16175](https://github.com/neovim/neovim/pull/16175) was merged just 5 hours ago so maybe this will be fixed for `nightly` users by neovim's next CI run? Otherwise it would probably be good at have a little guard against people running older version of neovim.

You are right, I just compiled the latest neovim and this problem is solved. Thanks.

**Comment by lewis6991** [comment]
Only 0.5.X or latest master is officially supported. If you want this fixed on an older 0.6 then PR's are welcome.

**Comment by clason** [comment]
(PSA: Neovim itself only supports 0.5.X or latest master, and the same should hold for plugins. If you grab the nightly tiger by the tail, you _have_ to keep holding on...)

**Comment by lewis6991** [comment]
27c783556dd3e4085a0a93063f242c888405d6b6 should stop old 0.6-dev installs breaking, though it is still recommended you upgrade to latest master or roll back to 0.5
