### ISSUE TITLE
error when opening neovim [after the encode/decode commit]

### ISSUE THREAD

**Issue by alexzanderr** [lewis6991/impatient.nvim#39]
i got this error:
```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:
243: attempt to call field 'encode' (a nil value)
```

my config hasnt been touched for 1 month.
the plugins i use were updated today ( i didnt look if impatient got any updates )
so my config is fine.

**EDIT**
my config:

- packer config
```lua
    use {
        "lewis6991/impatient.nvim"
        -- 	config = {
        -- 		-- Move to lua dir so impatient.nvim can cache it
        -- 		compile_path = vim.fn.stdpath('config')..'init.lua.d/lua/packer_compiled.lua'
        -- 	}
    }
```

- init.lua
```lua
require('impatient')
```
before loading all my plugins and config i load `impatient`

i had this config for a long time, long time no problem, but now, i get this stupid error

**Comment by lewis6991** [comment]
What's your Neovim version? Note only 0.5.x and latest master is supported.

**Comment by alexzanderr** [comment]
`NVIM v0.6.0-dev+402-g655e489e9`; and i used this version before and it working with impatient with no problem.

**Comment by lewis6991** [comment]
That version is not supported. Please update to 0.5.x or master with SHA newer than `a141f6e92`.

> and i used this version before and it working with impatient with no problem.

So? If you're using a dev version of Neovim, you should expect things to break.

**Comment by lewis6991** [comment]
Duplicate of #38

**Comment by alexzanderr** [comment]
> That version is not supported. Please update to 0.5.x or master with SHA newer than `a141f6e92`.
> 
> > and i used this version before and it working with impatient with no problem.
> 
> So? If you're using a dev version of Neovim, you should expect things to break.

so? i used this dev version and worked perfectly just before you updated this repo with the commit that has changes with `encode` and `decode`.

literally, yesterday was working.

**Comment by alexzanderr** [comment]
renaming back to `pack` and `unpack` doesnt fix the issue?

**Comment by alexzanderr** [comment]
cmon man. my entire neovim workflow depends on your plugin.

**Comment by lewis6991** [comment]
> so? i used this dev version and worked perfectly just before you updated this repo with the commit that has changes with encode and decode.

So you're saying if the plugin worked before on a specific SHA of Neovim, then every update of the plugin should always be compatible with this specific SHA? Sorry...sincerely... but it doesn't work like this. Support is only provided for the last official release and latest master.

> cmon man. my entire neovim workflow depends on your plugin.

Here are your options:
1. Downgrade your Neovim install to 0.5.0 or 0.5.1
2. Upgrade your Neovim install to SHA newer than `a141f6e92`
3. Use a fixed SHA of Impatient that works for your Neovim install. (If you can't change your Neovim version and you're running a dev version, then I'd suggest you do this for all your plugins).
4. Fix impatient for your dev version of Neovim and open a PR.
5. You can use the `cachepack` module:
    ```lua
    _G.use_cachepack = true
    require('impatient')
    ```

**Comment by lewis6991** [comment]
27c783556dd3e4085a0a93063f242c888405d6b6 will automatically use option 5 from above.

**Comment by alexzanderr** [comment]
option 5 its working. wow. thanks man.

**Comment by alexzanderr** [comment]
btw. yesterday i got this idea.

my neovim is built from source. so my package manager its not updating it to the latest.

i saw yesterday that some pull request was merged into neovim's head that had the same change that you made (maybe where you got your inspiration)

and i think if i update to the latest 0.6 commit and install the latest version of your plugin, maybe it will not break anymore.

**Comment by lewis6991** [comment]
> and i think if i update to the latest 0.6 commit

Yes, that was option 2

**Comment by alexzanderr** [comment]
oh. okey. thanks a lot for support
