### ISSUE TITLE
`DistantInstall` fails

### ISSUE THREAD

**Issue by axieax** [lewis6991/impatient.nvim#52]
Hi, found this weird bug a while ago, but for some reason, [distant.nvim](https://github.com/chipsenkbeil/distant.nvim)'s `DistantInstall` command fails if I enable profiling with `impatient.enable_profile()`, but works completely fine with profiling disabled (default).

I get the following error message:
```
...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:231: attempt to index a nil value...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:231: attempt to index a nil value...c
k/packer/start/impatient.nvim/lua/impatient/profile.lua:231: attempt to index a nil value...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:231: attempt to index a nil value...ck/pa
cker/start/impatient.nvim/lua/impatient/profile.lua:231: attempt to index a nil value
```

**Comment by lewis6991** [comment]
Not able to reproduce. I installed distant.nvim and ran `LuaCacheProfile` and there is no error.

**Comment by axieax** [comment]
Seems like I'm unable to reproduce this issue either, so consider it resolved :D

**Comment by OlegGulevskyy** [comment]
@axieax 
I am able to reproduce the error
What can be provided to help debug this?

**Comment by lewis6991** [comment]
Not a lot really. You'll need to debug it yourself.

It is honestly better just to disable profiling.
