### ISSUE TITLE
Loading impatient with packer

### ISSUE THREAD

**Issue by mosheavni** [lewis6991/impatient.nvim#54]
Hi, I'm new to lua, started using Packer to install packages.
I saw an option to run a command with the installation, and I wonder why it's not documented here.

```lua
  use {
    'lewis6991/impatient.nvim',
    config = function() require('impatient').setup() end
  }
```

Wouldn't it work?
Thanks.

**Comment by lewis6991** [comment]
No, doesn't work. The require needs to run much earlier in the init sequence as documented.
