### ISSUE TITLE
 Failed to load so after git pull 

### ISSUE THREAD

**Issue by wasden** [lewis6991/impatient.nvim#57]
This commit works fine for me (https://github.com/lewis6991/impatient.nvim/commit/2337df7d778e17a58d8709f651653b9039946d8d). 
But after I checkout to this commit (https://github.com/lewis6991/impatient.nvim/commit/af0575e07c635f7a7a99dae79543d629125a98d4) , it cannot handle so. 
Error as shown:
![Screenshot_20220521_201354](https://user-images.githubusercontent.com/26076025/169651154-868c64b5-eb3b-4381-a5cb-c02cd8547732.png)
This is error info after I checkout to https://github.com/lewis6991/impatient.nvim/commit/3680f3a27eee0e2995a58c5d7a975e6b0e8041e2
![image](https://user-images.githubusercontent.com/26076025/169651300-025be5a6-ce7c-4b93-94d6-29abeb6be366.png)
Log:
Loaded cache for path /home/huang/.local/share/nvim/site/pack/packer/opt/cmp-flypy.nvim/after/plugin/flypy.lua
Loaded cache for path /home/huang/.local/share/nvim/site/pack/packer/opt/cmp-flypy.nvim/lua/flypy.lua
No cache for path /home/huang/.local/share/nvim/site/pack/packer/opt/cmp-flypy.nvim/lua/libflypy.so

**Comment by lewis6991** [comment]
Have you tried clearing the cache?

**Comment by wasden** [comment]
Thanks! That worked!
