### ISSUE TITLE
Mac OSX Issues

### ISSUE THREAD

**Issue by axieax** [lewis6991/impatient.nvim#58]
I've encountered a lot of issues with my Neovim v0.6 [config](https://github.com/axieax/dotconfig/tree/main/nvim/lua/axie) on my Mac. However, it seemed like disabling this plugin resolved all of my issues for some reason - not sure why though. Would love to still use this plugin as it significantly reduces my start up time (especially on Mac).

Format on save autocmd (in lsp/options.lua) due to `vim.lsp.buf.formatting_sync()`:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/62098008/169841948-6728ca71-9225-424e-8ff8-562d6fff444a.png">

nvim start:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62098008/169842002-c93c0604-feaa-4372-af10-7a863be587c4.png">

Saving another opened buffer:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/62098008/169842323-d725d90b-b6c2-4553-a6a9-c6cd7759238f.png">

**Comment by lewis6991** [comment]
Have you tried clearing the cache?

**Comment by axieax** [comment]
> Have you tried clearing the cache?

Oh that was an easy fix. Thanks for the quick response!
