### ISSUE TITLE
mkdnflow.nvim not loaded correctly with impatient.nvim

### ISSUE THREAD

**Issue by kraxli** [lewis6991/impatient.nvim#67]
I have filed a bug report with [mkdnflow.nvim issue 49](https://github.com/jakewvincent/mkdnflow.nvim/issues/49) since the plugin is not working correctly. @jakewvincent  was able to track the error down to `impatient.nvim`
```
packer.nvim: Error running config for mkdnflow.nvim: ...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:216: attempt to index a nil value
```
Commenting out `impatient.nvim` solves the problem.

I am runngin `Nvim 0.7` on `Linux Mint 20/Ubuntu` using `Zsh-shell`. My config is based on [AstroNvim](https://github.com/AstroNvim/AstroNvim) and you can find my personal config on [nvim-config-astroVim/tree/mkdnflow_test](https://github.com/kraxli/nvim-config-astroVim/tree/mkdnflow_test)

**Comment by lewis6991** [comment]
Just disable profiling.

I won't be investigating this if there isn't a minimal testcase as I simply don't have the time.

**Comment by kraxli** [comment]
Sure I understand. After deleting any potential caching, it worked. Will investigate a bit further what the real root cause is

**Comment by avucic** [comment]
> Sure I understand. After deleting any potential caching, it worked. Will investigate a bit further what the real root cause is

@kraxli 

I have the same issue. How did you manage to fix that? What cache you deleted? I tried with `LuaCacheClear`..same thing..

**Comment by kraxli** [comment]
I have been able to solve it temporarily only and gave up - sorry for not been more helpful

**Comment by rockneverdies55** [comment]
Same thing here. Will disable profiling :-(
