### ISSUE TITLE
impatient.nvim and vim-plug

### ISSUE THREAD

**Issue by luetage** [lewis6991/impatient.nvim#72]
I haven’t seen this mentioned here. I used vim-plug as package manager before making the switch to packer. The impatient readme only mentions instructions for packer, but I tried impatient out on both managers to compare the results, otherwise same plugins and settings.  Startup times tested with [vim-startuptime](https://github.com/rhysd/vim-startuptime) (command line program). Mentioned times are averages after 10 loads.

* vim-plug: In init.lua I loaded options, then required my plugin setup file and in this file required impatient directly after `plug#end`
    without impatient: 126ms
    with impatient: 84ms
* packer: Startup with compiled packer file and required impatient at top of init.lua. No lazy loaded plugins.
    without impatient: 121ms
    with impatient: 82ms
    
I’d argue it’s perfectly viable to run impatient in combination with vim-plug on a modern neovim setup with lua config. I probably won’t go back to vim-plug, but it could be mentioned in the readme. The savings are comparable.

**Comment by lewis6991** [comment]
People can use any plugin manager they want. The README just specifies packer as an example. It isn't a goal to specify instructions for every plugin manager.

**Comment by luetage** [comment]
I understand that now. But reading the instructions it isn’t obvious. I thought I am forced to use packer, or it won’t work.
