### ISSUE TITLE
trailing data in  msgpack string

### ISSUE THREAD

**Issue by gegoune** [lewis6991/impatient.nvim#9]
Installed this plugin with packer with mpack luarock and added `require('impatient')` to the top of my init.lua file, getting following error on each nvim start now:

```
Error detected while processing /Users/<me>/<…>/nvim/init.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:121: trailing data in
 msgpack string
Press ENTER or type command to continue
```

How could I debug it?

**Comment by lewis6991** [comment]
Maybe reduce down the plugin list and make sure to delete the cache each time.

**Comment by gegoune** [comment]
Just removing `luacache` file gotten rid of error message and quite a few ms from startup time! Great thanks!

**Comment by shadmansaleh** [comment]
@lewis6991 there will probably always be cases where cache got corrupted or fails to load . I think it'll be best if you use `pcall` on the load calls and just mark the cache dirty when they fails.

https://github.com/lewis6991/impatient.nvim/blob/c21babb3bbb5f7730143b4346784227436bb7b8b/lua/impatient.lua#L120-L121
